version: 1.3.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  project: Wox.sln
after_test:
- ps: Copy-Item $env:APPDATA\Wox\Logs\*\*.txt .
- ps: ls Output\Packages
artifacts:
- path: 'Output\Packages\Wox-*.zip'
  name: installer
- path: 'Output\Packages\Wox.Plugin.*.nupkg'
  name: nuget_package
- path: 'Output\Packages\Wox.*.*'
  name: installer
- path: 'Output\Packages\Wox-*.*'
  name: installer
- path: 'Output\Packages\RELEASES'
  name: installer
- path: '*-*-*.txt'
  name: information
deploy:
  provider: NuGet
  api_key:
    secure: yybUOFgBuGVpbmOVZxsurC8OpkClzt9dR+/54WpMWcq6b6oyMatciaelRPnXsjRn
  artifact: nuget_package
  on:
    branch: api