version: 1.1.1.{build}
configuration:
    Release

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

build:
    project: Wox.sln

after_test:
    - ps: .\deploy\nuget\pack.ps1
    - cmd: .\deploy\UpdateGenerator\build.bat
    #- cmd: .\deploy\Cleanup.bat

deploy:
    provider: NuGet
    api_key:
        secure: yybUOFgBuGVpbmOVZxsurC8OpkClzt9dR+/54WpMWcq6b6oyMatciaelRPnXsjRn
    artifact: nugetpackage
    on:
        branch: master

artifacts:
    - path: Output\Release
      name: release-binary 

    - path: '*.nupkg'
      name: nugetpackage

    - path: Output\Update
      name: update-binary
