version: 1.3.{build}
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - ps: nuget restore
build:
  project: Wox.sln
after_test:
  - ps: Copy-Item $env:APPDATA\Wox\Logs\*\*.txt .
  - ps: powershell.exe -NoProfile -ExecutionPolicy Bypass -File Scripts\post_build.ps1
artifacts:
  - path: '*-*-*.txt'
    name: information
  - path: 'Output\Packages\Wox-*.zip'
    name: installer
  - path: 'Output\Packages\Wox.Plugin.*.nupkg'
    name: nuget_package
  - path: 'Output\Packages\Wox.*.*'
    name: installer
  - path: 'Output\Packages\Wox-*.*'
    name: installer
  - path: 'Output\Packages\RELEASES'
